#ifndef __S2_CISCO_SX80_DRIVE_V1_4_4__2_SERIES_ONLY__H__
#define __S2_CISCO_SX80_DRIVE_V1_4_4__2_SERIES_ONLY__H__



/*
* STRUCTURE S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only___CALLS
*/
#define CALLS__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__DISPLAYNAME_STRING_MAX_LEN 50
#define CALLS__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__REMOTENUMBER_STRING_MAX_LEN 100
#define CALLS__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALLTYPE_STRING_MAX_LEN 20
#define CALLS__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__STATUS_STRING_MAX_LEN 25
START_STRUCTURE_DEFINITION( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS )
{
   CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS__DISPLAYNAME, CALLS__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__DISPLAYNAME_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS__DISPLAYNAME );
   CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS__REMOTENUMBER, CALLS__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__REMOTENUMBER_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS__REMOTENUMBER );
   CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS__CALLTYPE, CALLS__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALLTYPE_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS__CALLTYPE );
   CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS__STATUS, CALLS__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__STATUS_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS__STATUS );
   unsigned short CALLS__CALLID;
   unsigned short CALLS__CONNECTED;
   unsigned short CALLS__ONHOLD;
};

/*
* STRUCTURE S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only___PHONEBOOK
*/
#define PHONEBOOK__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SENTRYNAME_STRING_MAX_LEN 100
#define PHONEBOOK__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SFOLDERID_STRING_MAX_LEN 100
START_STRUCTURE_DEFINITION( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, PHONEBOOK )
{
   CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, PHONEBOOK__SENTRYNAME, PHONEBOOK__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SENTRYNAME_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, PHONEBOOK__SENTRYNAME );
   CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, PHONEBOOK__SFOLDERID, PHONEBOOK__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SFOLDERID_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, PHONEBOOK__SFOLDERID );
   unsigned short PHONEBOOK__IPARENTFOLDER;
   unsigned short PHONEBOOK__IFIRSTCHILD;
   unsigned short PHONEBOOK__ICHILDCOUNT;
};

/*
* STRUCTURE S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only___CONTACTMETHOD
*/
#define CONTACTMETHOD__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCONTACTNUMBER_STRING_MAX_LEN 100
#define CONTACTMETHOD__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLRATE_STRING_MAX_LEN 20
#define CONTACTMETHOD__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLPROTOCOL_STRING_MAX_LEN 10
START_STRUCTURE_DEFINITION( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CONTACTMETHOD )
{
   CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CONTACTMETHOD__SCONTACTNUMBER, CONTACTMETHOD__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCONTACTNUMBER_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CONTACTMETHOD__SCONTACTNUMBER );
   CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CONTACTMETHOD__SCALLRATE, CONTACTMETHOD__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLRATE_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CONTACTMETHOD__SCALLRATE );
   CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CONTACTMETHOD__SCALLPROTOCOL, CONTACTMETHOD__S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLPROTOCOL_STRING_MAX_LEN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CONTACTMETHOD__SCALLPROTOCOL );
};


/*
* Constructor and Destructor
*/
int S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALLS_Constructor ( START_STRUCTURE_DEFINITION( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS ) * me, int nVerbose );
int S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALLS_Destructor ( START_STRUCTURE_DEFINITION( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS ) * me, int nVerbose );
int S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONEBOOK_Constructor ( START_STRUCTURE_DEFINITION( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, PHONEBOOK ) * me, int nVerbose );
int S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONEBOOK_Destructor ( START_STRUCTURE_DEFINITION( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, PHONEBOOK ) * me, int nVerbose );
int S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONTACTMETHOD_Constructor ( START_STRUCTURE_DEFINITION( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CONTACTMETHOD ) * me, int nVerbose );
int S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONTACTMETHOD_Destructor ( START_STRUCTURE_DEFINITION( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CONTACTMETHOD ) * me, int nVerbose );

/*
* DIGITAL_INPUT
*/
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__GET_PROCESSOR_INFO_DIG_INPUT 0
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_CAMERA_PRESET_GO_DIG_INPUT 1
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_CAMERA_TILT_UP_DIG_INPUT 2
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_CAMERA_TILT_DOWN_DIG_INPUT 3
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_CAMERA_PAN_LEFT_DIG_INPUT 4
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_CAMERA_PAN_RIGHT_DIG_INPUT 5
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_CAMERA_ZOOM_IN_DIG_INPUT 6
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_CAMERA_ZOOM_OUT_DIG_INPUT 7
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_CAMERA_STOP_DIG_INPUT 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_SELECT_SOURCE_GO_DIG_INPUT 9
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__DIAL_DIG_INPUT 10
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__ANSWER_INCOMING_CALL_DIG_INPUT 11
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__REJECT_INCOMING_CALL_DIG_INPUT 12
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__GET_PHONE_BOOK_DIG_INPUT 13
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__TOP_LEVEL_DIG_INPUT 14
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__UP_ONE_LEVEL_DIG_INPUT 15
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_DIAL_DIG_INPUT 16
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_CLEAR_SELECTED_DIG_INPUT 17
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SIP_ENABLED_DIG_INPUT 18
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__H323_ENABLED_DIG_INPUT 19
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__ENABLE_CALL_DISCONNECT_DELAY_DIG_INPUT 20
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__JOIN_DIG_INPUT 21
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__HOLD_ALL_DIG_INPUT 22
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__RESUME_ALL_DIG_INPUT 23
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PICTURE_LAYOUT_CUSTOM_DIG_INPUT 24

#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__HANG_UP_CALL_DIG_INPUT 25
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__HANG_UP_CALL_ARRAY_LENGTH 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__HOLD_CALL_DIG_INPUT 33
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__HOLD_CALL_ARRAY_LENGTH 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__RESUME_CALL_DIG_INPUT 41
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__RESUME_CALL_ARRAY_LENGTH 8

/*
* ANALOG_INPUT
*/
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_CAMERA_PRESET_NUMBER_IN_ANALOG_INPUT 0
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_SELECT_NUMBER_IN_ANALOG_INPUT 1
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FAR_END_SOURCE_NUMBER_IN_ANALOG_INPUT 2
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__VOLUME_LEVEL_IN_ANALOG_INPUT 3
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_SELECT_ENTRY_IN_ANALOG_INPUT 4

#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALL_RATE_STRING_INPUT 7
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALL_RATE_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CALL_RATE, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALL_RATE_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALL_PROTOCOL_STRING_INPUT 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALL_PROTOCOL_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CALL_PROTOCOL, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALL_PROTOCOL_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALL_TYPE_STRING_INPUT 9
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALL_TYPE_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CALL_TYPE, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CALL_TYPE_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__DIAL_NUMBER_STRING_INPUT 10
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__DIAL_NUMBER_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __DIAL_NUMBER, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__DIAL_NUMBER_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PICTURE_LAYOUT_CUSTOM_NAME_IN_STRING_INPUT 11
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PICTURE_LAYOUT_CUSTOM_NAME_IN_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __PICTURE_LAYOUT_CUSTOM_NAME_IN, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PICTURE_LAYOUT_CUSTOM_NAME_IN_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__DTMF_KEY_STRING_INPUT 12
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__DTMF_KEY_STRING_MAX_LEN 1
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __DTMF_KEY, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__DTMF_KEY_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_TYPE_IN_STRING_INPUT 13
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_TYPE_IN_STRING_MAX_LEN 25
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __PHONE_BOOK_TYPE_IN, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_TYPE_IN_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_SEARCH_TEXT_IN_STRING_INPUT 14
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_SEARCH_TEXT_IN_STRING_MAX_LEN 50
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __PHONE_BOOK_SEARCH_TEXT_IN, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_SEARCH_TEXT_IN_STRING_MAX_LEN );

#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FROM_CONSOLE_BUFFER_INPUT 5
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FROM_CONSOLE_BUFFER_MAX_LEN 200
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __FROM_CONSOLE, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FROM_CONSOLE_BUFFER_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FROM_DEVICE_BUFFER_INPUT 6
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FROM_DEVICE_BUFFER_MAX_LEN 30000
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __FROM_DEVICE, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__FROM_DEVICE_BUFFER_MAX_LEN );


/*
* DIGITAL_OUTPUT
*/
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__INCOMING_CALL_FB_DIG_OUTPUT 0
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_DOWNLOAD_BUSY_DIG_OUTPUT 1
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_AT_TOP_LEVEL_DIG_OUTPUT 2
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SELECTED_ITEM_IS_CONTACT_DIG_OUTPUT 3
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SEARCH_IS_BUSY_DIG_OUTPUT 4
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_ALERT_ISACTIVE_DIG_OUTPUT 5
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_ISACTIVE_DIG_OUTPUT 6
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION1_ISACTIVE_DIG_OUTPUT 7
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION2_ISACTIVE_DIG_OUTPUT 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION3_ISACTIVE_DIG_OUTPUT 9
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION4_ISACTIVE_DIG_OUTPUT 10
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION5_ISACTIVE_DIG_OUTPUT 11

#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_CONNECTED_DIG_OUTPUT 12
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_CONNECTED_ARRAY_LENGTH 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_IS_ON_HOLD_DIG_OUTPUT 20
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_IS_ON_HOLD_ARRAY_LENGTH 8

/*
* ANALOG_OUTPUT
*/
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_SELECTED_NUMBER_VALUE_ANALOG_OUTPUT 0
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__VOLUME_LEVEL_FB_OUT_ANALOG_OUTPUT 1
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_TOTAL_ROWS_ANALOG_OUTPUT 2
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__NUMBER_OF_ACTIVE_CALLS_ANALOG_OUTPUT 3

#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__TO_CONSOLE_STRING_OUTPUT 4
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__TO_DEVICE_STRING_OUTPUT 5
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__TO_MODULE_STRING_OUTPUT 6
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__INCOMING_CALL_DISPLAY_NAME_STRING_OUTPUT 7
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__INCOMING_CALL_REMOTE_NUMBER_STRING_OUTPUT 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__INCOMING_CALL_CALL_TYPE_STRING_OUTPUT 9
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__INCOMING_CALL_CALL_ID_STRING_OUTPUT 10
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SELECTED_ENTRY_NAME_TEXT_STRING_OUTPUT 11
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SELECTED_ENTRY_NUMBER_TEXT_STRING_OUTPUT 12
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_FOLDER_NAME_TEXT_STRING_OUTPUT 13
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_ALERT_TEXT_STRING_OUTPUT 14
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_TITLE_STRING_OUTPUT 15
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_TEXT_STRING_OUTPUT 16
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION1_TEXT_STRING_OUTPUT 17
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION2_TEXT_STRING_OUTPUT 18
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION3_TEXT_STRING_OUTPUT 19
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION4_TEXT_STRING_OUTPUT 20
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__MESSAGE_PROMPT_OPTION5_TEXT_STRING_OUTPUT 21
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SYSTEM_NAME_STRING_OUTPUT 22
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SYSTEM_IP_ADDRESS_STRING_OUTPUT 23
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SYSTEM_H323_ID_STRING_OUTPUT 24
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SYSTEM_E164_ALIAS_STRING_OUTPUT 25
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SYSTEM_SIP_URI_STRING_OUTPUT 26

#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_DISPLAY_NAME_STRING_OUTPUT 27
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_DISPLAY_NAME_ARRAY_LENGTH 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_REMOTE_NUMBER_STRING_OUTPUT 35
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_REMOTE_NUMBER_ARRAY_LENGTH 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_STATUS_STRING_OUTPUT 43
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_STATUS_ARRAY_LENGTH 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_CALL_TYPE_STRING_OUTPUT 51
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_CALL_TYPE_ARRAY_LENGTH 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_CALL_ID_STRING_OUTPUT 59
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTED_CALL_CALL_ID_ARRAY_LENGTH 8
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_ENTRY_NAME_TEXT_STRING_OUTPUT 67
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PHONE_BOOK_ENTRY_NAME_TEXT_ARRAY_LENGTH 251

/*
* Direct Socket Variables
*/




/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* INTEGER_PARAMETER
*/
/*
* SIGNED_INTEGER_PARAMETER
*/
/*
* LONG_INTEGER_PARAMETER
*/
/*
* SIGNED_LONG_INTEGER_PARAMETER
*/
/*
* STRING_PARAMETER
*/


/*
* INTEGER
*/
CREATE_INTARRAY1D( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __ISEARCHRESULTS, 50 );;


/*
* LONG_INTEGER
*/


/*
* SIGNED_INTEGER
*/


/*
* SIGNED_LONG_INTEGER
*/


/*
* STRING
*/
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SMACADDRESS_STRING_MAX_LEN 25
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SMACADDRESS, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SMACADDRESS_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SPROCESSORTYPE_STRING_MAX_LEN 50
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SPROCESSORTYPE, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SPROCESSORTYPE_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SFIRMWAREVERSION_STRING_MAX_LEN 50
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SFIRMWAREVERSION, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SFIRMWAREVERSION_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__STEMPRECEIVE_STRING_MAX_LEN 1000
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __STEMPRECEIVE, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__STEMPRECEIVE_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SPHONEBOOKTYPE_STRING_MAX_LEN 25
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SPHONEBOOKTYPE, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SPHONEBOOKTYPE_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SSEARCHTEXT_STRING_MAX_LEN 50
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SSEARCHTEXT, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SSEARCHTEXT_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLRATE_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SCALLRATE, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLRATE_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLTYPE_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SCALLTYPE, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLTYPE_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLPROTOCOL_STRING_MAX_LEN 20
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SCALLPROTOCOL, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SCALLPROTOCOL_STRING_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SDIALNUMBER_STRING_MAX_LEN 100
CREATE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SDIALNUMBER, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__SDIALNUMBER_STRING_MAX_LEN );

/*
* STRUCTURE
*/
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTEDCALL_STRUCT_MAX_LEN 8
CREATE_STRUCTURE_ARRAY( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CONNECTEDCALL, CALLS, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CONNECTEDCALL_STRUCT_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PBENTRIES_STRUCT_MAX_LEN 2000
CREATE_STRUCTURE_ARRAY( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __PBENTRIES, PHONEBOOK, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__PBENTRIES_STRUCT_MAX_LEN );
#define __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CMMETHODS_STRUCT_MAX_LEN 4000
CREATE_STRUCTURE_ARRAY( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CMMETHODS, CONTACTMETHOD, __S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only__CMMETHODS_STRUCT_MAX_LEN );

START_GLOBAL_VAR_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_ )
{
   void* InstancePtr;
   struct GenericOutputString_s sGenericOutStr;
   unsigned short LastModifiedArrayIndex;

   DECLARE_IO_ARRAY( __HANG_UP_CALL );
   DECLARE_IO_ARRAY( __HOLD_CALL );
   DECLARE_IO_ARRAY( __RESUME_CALL );
   DECLARE_IO_ARRAY( __CONNECTED_CALL_CONNECTED );
   DECLARE_IO_ARRAY( __CONNECTED_CALL_IS_ON_HOLD );
   DECLARE_IO_ARRAY( __CONNECTED_CALL_DISPLAY_NAME );
   DECLARE_IO_ARRAY( __CONNECTED_CALL_REMOTE_NUMBER );
   DECLARE_IO_ARRAY( __CONNECTED_CALL_STATUS );
   DECLARE_IO_ARRAY( __CONNECTED_CALL_CALL_TYPE );
   DECLARE_IO_ARRAY( __CONNECTED_CALL_CALL_ID );
   DECLARE_IO_ARRAY( __PHONE_BOOK_ENTRY_NAME_TEXT );
   unsigned short __ITOUCHEXPERIMENTAL;
   unsigned short __ITOUCHREGISTERED;
   unsigned short __ICONSOLESENT;
   unsigned short __ISELECTEDCALL;
   unsigned short __IFOUNDLAN;
   unsigned short __IPHONEBOOKDOWNLOADBUSY;
   unsigned short __IPHONEBOOKREQUESTOFFSET;
   unsigned short __IPHONEBOOKREQUESTLIMIT;
   unsigned short __IFLAG;
   unsigned short __IFOLDERREQUESTED;
   unsigned short __INEXTAVAILABLEENTRY;
   unsigned short __INEXTAVAILABLEMETHOD;
   unsigned short __FITEMPENTRYNUM;
   unsigned short __ILASTCONTACTITEM;
   unsigned short __ILASTCONTACTMETHOD;
   unsigned short __IRECEIVINGPHONEBOOK;
   unsigned short __ISELECTEDFOLDER;
   unsigned short __IFLAG1;
   unsigned short __IPHONEBOOKREQUESTERRORCOUNT;
   unsigned short __ISELECTEDENTRY;
   unsigned short __ISEARCHRESULTSCOUNT;
   unsigned short __ICONNECTEDCALLSCOUNT;
   unsigned short __ISEARCHACTIVE;
   unsigned short __ISEARCHBUSY;
   unsigned short __INEWSEARCHTEXT;
   unsigned short __IPROCESSINGSEARCHRESULTS;
   unsigned short __INOENTRIES;
   DECLARE_INTARRAY( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __ISEARCHRESULTS );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SMACADDRESS );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SPROCESSORTYPE );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SFIRMWAREVERSION );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __STEMPRECEIVE );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SPHONEBOOKTYPE );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SSEARCHTEXT );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SCALLRATE );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SCALLTYPE );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SCALLPROTOCOL );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __SDIALNUMBER );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CALL_RATE );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CALL_PROTOCOL );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CALL_TYPE );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __DIAL_NUMBER );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __PICTURE_LAYOUT_CUSTOM_NAME_IN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __DTMF_KEY );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __PHONE_BOOK_TYPE_IN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __PHONE_BOOK_SEARCH_TEXT_IN );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __FROM_CONSOLE );
   DECLARE_STRING_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __FROM_DEVICE );
   DECLARE_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, CALLS, __INCOMINGCALL );
   DECLARE_STRUCT_ARRAY( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CONNECTEDCALL );
   DECLARE_STRUCT_ARRAY( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __PBENTRIES );
   DECLARE_STRUCT_ARRAY( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, __CMMETHODS );
};

START_NVRAM_VAR_STRUCT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_ )
{
};

DEFINE_WAITEVENT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, WTOUCHWAIT );
DEFINE_WAITEVENT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, WSEARCH );
DEFINE_WAITEVENT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, WPHONEBOOKREQUESTTIMEOUT );
DEFINE_WAITEVENT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, WCLEARINCOMINGCALL );
DEFINE_WAITEVENT( S2_Cisco_SX80_Drive_v1_4_4__2_Series_Only_, WCLEARDISCONENCTEDCALL );


#endif //__S2_CISCO_SX80_DRIVE_V1_4_4__2_SERIES_ONLY__H__

